/* ship type: 1=>駆逐, 2=>軽巡, 3=>重巡, 4=>超巡, 5=>巡洋戦艦, 6=>戦艦, 7=>軽母, 8=>空母, 9=>航戦 */
/* equip type: 1->small, 2->medium, 3->large, 4->torpedo, 5->air, 6->fight, 7->bomb, 8->attack, 9->aux */
export const shiplist = {
  remove: {
    text: "remove",
    bg: "",
    fr: "",
    icon: "ui/empty.png",
    equip: [[0], [0], [0], [0], [0]],
  },
  /*---------------------------------------------------------*/
  キアサージ: {
    text: "キアサージ",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/199040.png",
    type: 9,
    rarity: "UR",
    equip: [[3], [6], [5], [9], [9]],
  },
  アルザス: {
    text: "アルザス",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/805030.png",
    type: 6,
    rarity: "UR",
    equip: {
      equip_1: [3],
      equip_2: [1, 2],
      equip_3: [5],
      equip_4: [9],
      equip_5: [9],
    },
  },
  ソビエツキーソユーズ: {
    text: "ソビエツキーソユーズ",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/705020.png",
    type: 6,
    rarity: "UR",
    equip: {
      equip_1: [3],
      equip_2: [1, 2],
      equip_3: [5],
      equip_4: [9],
      equip_5: [9],
    },
  },
  ビスマルクZwei: {
    text: "ビスマルクZwei",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/bisimaiz.png",
    type: 6,
    rarity: "UR",
    equip: {
      equip_1: [3],
      equip_2: [1, 2],
      equip_3: [5],
      equip_4: [9],
      equip_5: [9],
    },
  },
  フリドリヒデアグローセ: {
    text: "フリドリヒデアグローセ",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/feiteliedadi.png",
    type: 6,
    rarity: "UR",
    equip: {
      equip_1: [3],
      equip_2: [1, 2],
      equip_3: [5],
      equip_4: [9],
      equip_5: [9],
    },
  },
  ヴァンガード: {
    text: "ヴァンガード",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/qianwei.png",
    type: 6,
    rarity: "UR",
    equip: {
      equip_1: [3],
      equip_2: [1, 2],
      equip_3: [5],
      equip_4: [9],
      equip_5: [9],
    },
  },
  ウルリッヒフォンフッテン: {
    text: "ウルリッヒフォンフッテン",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/wuerlixi.png",
    type: 6,
    rarity: "UR",
    equip: {
      equip_1: [3],
      equip_2: [1, 2],
      equip_3: [5],
      equip_4: [9],
      equip_5: [9],
    },
  },
  武蔵: {
    text: "武蔵",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/wuzang.png",
    type: 6,
    rarity: "UR",
    equip: {
      equip_1: [3],
      equip_2: [1, 2],
      equip_3: [5],
      equip_4: [9],
      equip_5: [9],
    },
  },
  ニュージャージ: {
    text: "ニュージャージ",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/xinzexi.png",
    type: 6,
    rarity: "UR",
    equip: {
      equip_1: [3],
      equip_2: [1, 2],
      equip_3: [5],
      equip_4: [9],
      equip_5: [9],
    },
  },
  ウォースパイト改: {
    text: "ウォースパイト改",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/yanzhan_g.png",
    type: 6,
    rarity: "UR",
    equip: {
      equip_1: [3],
      equip_2: [1, 2],
      equip_3: [5],
      equip_4: [9],
      equip_5: [9],
    },
  },
  /*---------------------------------------------------------*/
  信濃: {
    text: "信濃",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_kuubo/UR/xinnong.png",
    type: 8,
    rarity: "UR",
    equip: [[6, 7, 8], [7], [8], [9], [9]],
  },
  白龍: {
    text: "白龍",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_kuubo/UR/bailong.png",
    type: 8,
    rarity: "UR",
    equip: {
      equip_1: [6, 8],
      equip_2: [7],
      equip_3: [7, 8],
      equip_4: [9],
      equip_5: [9],
    },
  },
  インプラカブル: {
    text: "インプラカブル",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_kuubo/UR/yuanchou.png",
    type: 8,
    rarity: "UR",
    equip: {
      equip_1: [6],
      equip_2: [6, 7, 8],
      equip_3: [8],
      equip_4: [9],
      equip_5: [9],
    },
  },
  ヨークタウンⅡ: {
    text: "ヨークタウンⅡ",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_kuubo/UR/yuekechengii.png",
    type: 8,
    rarity: "UR",
    equip: {
      equip_1: [6],
      equip_2: [7],
      equip_3: [6, 7, 8],
      equip_4: [9],
      equip_5: [9],
    },
  },
  アドミラルナヒーモフ: {
    text: "アドミラルナヒーモフ",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_kuubo/UR/799020.png",
    type: 8,
    rarity: "UR",
    equip: {
      equip_1: [6],
      equip_2: [6, 7, 8],
      equip_3: [8],
      equip_4: [9],
      equip_5: [9],
    },
  },
};
