export const shiplist = {
  キアサージ: {
    name: "キアサージ",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/199040.png",
    type: "senkan",
    rarity: "UR",
  },
  アルザス: {
    name: "アルザス",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/805030.png",
    type: "senkan",
    rarity: "UR",
  },
  ソユーズ: {
    name: "ソユーズス",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/705020.png",
    type: "senkan",
    rarity: "UR",
  },
  ビスマルクZwei: {
    name: "ビスマルクZwei",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/bisimaiz.png",
    type: "senkan",
    rarity: "UR",
  },
  グローセ: {
    name: "グローセ",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/feiteliedadi.png",
    type: "senkan",
    rarity: "UR",
  },
  ヴァンガード: {
    name: "ヴァンガード",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/qianwei.png",
    type: "senkan",
    rarity: "UR",
  },
  フッテン: {
    name: "フッテン",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/wuerlixi.png",
    type: "senkan",
    rarity: "UR",
  },
  武蔵: {
    name: "武蔵",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/wuzang.png",
    type: "senkan",
    rarity: "UR",
  },
  ニュージャージ: {
    name: "ニュージャージ",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/xinzexi.png",
    type: "senkan",
    rarity: "UR",
  },
};
