/* type: 1=>駆逐, 2=>軽巡, 3=>重巡, 4=>超巡, 5=>巡洋戦艦, 6=>戦艦, 7=>軽母, 8=>空母, 9=>航戦 */
/* equip: 1=> */
export const shiplist = {
  remove: {
    text: "remove",
    bg: "",
    fr: "",
    icon: "ui/empty.png",
  },
  キアサージ: {
    text: "キアサージ",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/199040.png",
    type: "6",
    rarity: "UR",
    equip: {
      main: ["large"],
      sub: ["medium", "small"],
      aux: ["back", "all"],
    },
  },
  アルザス: {
    text: "アルザス",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/805030.png",
    type: "6",
    rarity: "UR",
  },
  ソユーズ: {
    text: "ソユーズ",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/705020.png",
    type: "6",
    rarity: "UR",
  },
  ビスマルクZwei: {
    text: "ビスマルクZwei",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/bisimaiz.png",
    type: "6",
    rarity: "UR",
  },
  グローセ: {
    text: "グローセ",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/feiteliedadi.png",
    type: "6",
    rarity: "UR",
  },
  ヴァンガード: {
    text: "ヴァンガード",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/qianwei.png",
    type: "6",
    rarity: "UR",
  },
  フッテン: {
    text: "フッテン",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/wuerlixi.png",
    type: "6",
    rarity: "UR",
  },
  武蔵: {
    text: "武蔵",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/wuzang.png",
    type: "6",
    rarity: "UR",
  },
  ニュージャージ: {
    text: "ニュージャージ",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "ship_senkan/UR/xinzexi.png",
    type: "6",
    rarity: "UR",
  },
};
