/* ship type: 1=>駆逐, 2=>軽巡, 3=>重巡, 4=>超巡, 5=>巡洋戦艦, 6=>戦艦, 7=>軽母, 8=>空母, 9=>航戦 */
/* equip type: 1->small, 2->medium, 3->large, 4->torpedo, 5->air, 6->fight, 7->bomb, 8->attack */
export const weaponlist = {
  remove: {
    text: "remove",
    bg: "",
    fr: "",
    icon: "ui/icon_back.png",
  },
  /*UR---------------------------------------------------------*/
  "406mm三連装砲MK7T0": {
    text: "406mm三連装砲MK7T0",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "equips/large/14400.png",
    type: 3,
    rarity: "UR",
  },
  試作型457mm連装砲MKAT0: {
    text: "試作型457mm連装砲MKAT0",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "equips/large/14500.png",
    type: 3,
    rarity: "UR",
  },
  "460mm三連装砲T0": {
    text: "460mm三連装砲T0",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "equips/large/34200.png",
    type: 3,
    rarity: "UR",
  },
  "試作型艦上式La-9T0": {
    text: "試作型艦上式La-9T0",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "equips/fight/85600.png",
    type: 6,
    rarity: "UR",
  },
  "AD-1スカイレーダー": {
    text: "AD-1スカイレーダー",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "equips/bomb/19300.png",
    type: 7,
    rarity: "UR",
  },
  "試作型天雷(特別計画艦仕様)T0": {
    text: "試作型天雷(特別計画艦仕様)T0",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "equips/bomb/39340.png",
    type: 7,
    rarity: "UR",
  },
  ワイヴァーンT0: {
    text: "ワイヴァーンT0",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "equips/attack/28400.png",
    type: 8,
    rarity: "UR",
  },
  試作型スピアフィッシュ: {
    text: "試作型スピアフィッシュ",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "equips/attack/28420.png",
    type: 8,
    rarity: "UR",
  },
  /*SSR---------------------------------------------------------*/
  試作型406mm三連装砲MkDT0: {
    text: "試作型406mm三連装砲MkDT0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/14360.png",
    type: 3,
    rarity: "SSR",
  },
  試作型406mm三連装砲Mk6改T0: {
    text: "試作型406mm三連装砲Mk6改T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/14540.png",
    type: 3,
    rarity: "SSR",
  },
  試作型406mm連装砲Mk4T0: {
    text: "試作型406mm連装砲Mk4T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/14520.png",
    type: 3,
    rarity: "SSR",
  },
  "356mm四連装砲T3": {
    text: "356mm四連装砲T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/24000.png",
    type: 3,
    rarity: "SSR",
  },
  試製381mm三連装砲T0: {
    text: "試製381mm三連装砲T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/24160.png",
    type: 3,
    rarity: "SSR",
  },
  "406mm三連装砲T3": {
    text: "406mm三連装砲T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/24200.png",
    type: 3,
    rarity: "SSR",
  },
  "381mm連装砲改T0": {
    text: "381mm連装砲改T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/24300.png",
    type: 3,
    rarity: "SSR",
  },
  "試作型410mm連装砲mod.A": {
    text: "試作型410mm連装砲mod.A",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/34320.png",
    type: 3,
    rarity: "SSR",
  },
  試製410mm三連装砲T0: {
    text: "試製410mm三連装砲T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/34180.png",
    type: 3,
    rarity: "SSR",
  },
  "410mm連装砲(三式弾)T0": {
    text: "410mm連装砲(三式弾)T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/34100.png",
    type: 3,
    rarity: "SSR",
  },
  "380mmSKC連装砲T3": {
    text: "380mmSKC連装砲T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/44100.png",
    type: 3,
    rarity: "SSR",
  },
  試作型406mmSKC連装砲T0: {
    text: "試作型406mmSKC連装砲T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/44200.png",
    type: 3,
    rarity: "SSR",
  },
  試作型305mmSKC39三連装砲T0: {
    text: "試作型305mmSKC39三連装砲T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/44300.png",
    type: 3,
    rarity: "SSR",
  },
  試作型380mmSKC三連装砲T0: {
    text: "試作型380mmSKC三連装砲T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/44500.png",
    type: 3,
    rarity: "SSR",
  },
  "380mm四連装砲Mle1935T3": {
    text: "380mm四連装砲Mle1935T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/50400.png",
    type: 3,
    rarity: "SSR",
  },
  試作型380mm三連装砲Mle1935T0: {
    text: "試作型380mm三連装砲Mle1935T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/50480.png",
    type: 3,
    rarity: "SSR",
  },
  "試作型406mm/50三連装砲T0": {
    text: "試作型406mm/50三連装砲T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/51000.png",
    type: 3,
    rarity: "SSR",
  },
  "381mm三連装砲Model1934T3": {
    text: "381mm三連装砲Model1934T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/55000.png",
    type: 3,
    rarity: "SSR",
  },
  試作型三連装406mm主砲Model1940T0: {
    text: "試作型三連装406mm主砲Model1940T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/55900.png",
    type: 3,
    rarity: "SSR",
  },
  "406mm三連装砲B-37 MK-1T3": {
    text: "406mm三連装砲B-37 MK-1T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/85300.png",
    type: 3,
    rarity: "SSR",
  },
  /*fight---------------------------------------------------------*/
  "F2Aバッファロー(サッチ隊)T0": {
    text: "F2Aバッファロー(サッチ隊)T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/17060.png",
    type: 6,
    rarity: "SSR",
  },
  "F4U(VF-17中隊)T0": {
    text: "F4U(VF-17中隊)T00",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/17260.png",
    type: 6,
    rarity: "SSR",
  },
  "試作型XF5U「フライングパンケーキ」": {
    text: "試作型XF5U「フライングパンケーキ」",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/17420.png",
    type: 6,
    rarity: "SSR",
  },
  F6FヘルキャットT3: {
    text: "F6FヘルキャットT3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/17300.png",
    type: 6,
    rarity: "SSR",
  },
  "F6Fヘルキャット(HVAR搭載型)": {
    text: "F6Fヘルキャット(HVAR搭載型)",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/17440.png",
    type: 6,
    rarity: "SSR",
  },
  F7FタイガーキャットT0: {
    text: "F7FタイガーキャットT0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/17360.png",
    type: 6,
    rarity: "SSR",
  },
  F8FベアキャットT0: {
    text: "F8FベアキャットT0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/17380.png",
    type: 6,
    rarity: "SSR",
  },
  "シーファイアFR.47T0": {
    text: "シーファイアFR.47T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/27060.png",
    type: 6,
    rarity: "SSR",
  },
  シーファングT3: {
    text: "シーファングT3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/27100.png",
    type: 6,
    rarity: "SSR",
  },
  シーフューリーT0: {
    text: "シーフューリーT0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/27300.png",
    type: 6,
    rarity: "SSR",
  },
  シーホーネットT0: {
    text: "シーホーネットT0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/27320.png",
    type: 6,
    rarity: "SSR",
  },
  零戦五二型T3: {
    text: "零戦五二型T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/37200.png",
    type: 6,
    rarity: "SSR",
  },
  烈風T3: {
    text: "烈風T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/37300.png",
    type: 6,
    rarity: "SSR",
  },
  紫電改二T0: {
    text: "紫電改二T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/37400.png",
    type: 6,
    rarity: "SSR",
  },
  試作型紫電改四T0: {
    text: "試作型紫電改四T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/37460.png",
    type: 6,
    rarity: "SSR",
  },
  "Me-155A艦上戦闘機T3": {
    text: "Me-155A艦上戦闘機T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/47100.png",
    type: 6,
    rarity: "SSR",
  },
  "試作型BF-109G(特別計画艦仕様)T0": {
    text: "試作型BF-109G(特別計画艦仕様)T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/47160.png",
    type: 6,
    rarity: "SSR",
  },
  "試作型FW-190 A-6/R6(艦載機型)": {
    text: "試作型FW-190 A-6/R6(艦載機型)",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/fight/47180.png",
    type: 6,
    rarity: "SSR",
  },
  /*bomb---------------------------------------------------------*/
  "SBD(マクラスキー隊)T0": {
    text: "SBD(マクラスキー隊)T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/bomb/19060.png",
    type: 7,
    rarity: "SSR",
  },
  "実験型XSB3C-1T0": {
    text: "実験型XSB3C-1T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/bomb/19160.png",
    type: 7,
    rarity: "SSR",
  },
  "BTD-1デストロイヤーT3": {
    text: "BTD-1デストロイヤーT3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/bomb/19200.png",
    type: 7,
    rarity: "SSR",
  },
  "バラクーダ(831中隊)T0": {
    text: "バラクーダ(831中隊)T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/bomb/29300.png",
    type: 7,
    rarity: "SSR",
  },
  ファイアフライT0: {
    text: "ファイアフライT0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/bomb/29200.png",
    type: 7,
    rarity: "SSR",
  },
  "ファイアフライ(1771中隊)T0": {
    text: "ファイアフライ(1771中隊)T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/bomb/29220.png",
    type: 7,
    rarity: "SSR",
  },
  彗星T3: {
    text: "彗星T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/bomb/39100.png",
    type: 7,
    rarity: "SSR",
  },
  彗星一二型甲T0: {
    text: "彗星一二型甲T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/bomb/39160.png",
    type: 7,
    rarity: "SSR",
  },
  "試作型艦上式Su-2": {
    text: "試作型艦上式Su-2",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/bomb/85540.png",
    type: 7,
    rarity: "SSR",
  },
  /*attack---------------------------------------------------------*/
  "TBDデバステイター(VT-8中隊)T0": {
    text: "TBDデバステイター(VT-8中隊)T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/attack/18060.png",
    type: 8,
    rarity: "SSR",
  },
  "TBFアベンジャー(VT-8中隊)T0": {
    text: "TBFアベンジャー(VT-8中隊)T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/attack/18060.png",
    type: 8,
    rarity: "SSR",
  },
  "TBMアベンジャー(VT-18中隊)T0": {
    text: "TBMアベンジャー(VT-18中隊)T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/attack/18180.png",
    type: 8,
    rarity: "SSR",
  },
  "XTB2D-1スカイパイレートT0": {
    text: "XTB2D-1スカイパイレートT0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/attack/18220.png",
    type: 8,
    rarity: "SSR",
  },
  "ソードフィッシュ(818中隊)T0": {
    text: "ソードフィッシュ(818中隊)T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/attack/28060.png",
    type: 8,
    rarity: "SSR",
  },
  バラクーダT3: {
    text: "バラクーダT3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/attack/28100.png",
    type: 8,
    rarity: "SSR",
  },
  ファイアブランドT0: {
    text: "ファイアブランドT0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/attack/28200.png",
    type: 8,
    rarity: "SSR",
  },
  ファイアクレストT0: {
    text: "ファイアクレストT0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/attack/28220.png",
    type: 8,
    rarity: "SSR",
  },
  流星T3: {
    text: "流星T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/attack/38200.png",
    type: 8,
    rarity: "SSR",
  },
  "試作型彩雲(艦攻型・特別計画艦仕様)T0": {
    text: "試作型彩雲(艦攻型・特別計画艦仕様)T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/attack/38300.png",
    type: 8,
    rarity: "SSR",
  },
  "Ju-87 D-4T0": {
    text: "Ju-87 D-4T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/attack/48040.png",
    type: 8,
    rarity: "SSR",
  },
  "ブレゲー BR.810攻撃機T0": {
    text: "ブレゲー BR.810攻撃機T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/attack/51240.png",
    type: 8,
    rarity: "SSR",
  },
  "試作型VIT-2(VK107)T0": {
    text: "試作型VIT-2(VK107)T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/attack/85560.png",
    type: 8,
    rarity: "SSR",
  },
  "試作型VIT-2（モードチェンジ）T0": {
    text: "試作型VIT-2（モードチェンジ）T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/attack/85620.png",
    type: 8,
    rarity: "SSR",
  },
};
