/* type: large, medium, small, air, front, back, all*/
/* large, fight, bomb, torpedo, equip*/
export const weaponlist = {
  remove: {
    text: "remove",
    bg: "",
    fr: "",
    icon: "ui/icon_back.png",
  },
  "406mm三連装砲MK7T0": {
    text: "406mm三連装砲MK7T0",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "equips/large/14400.png",
    type: "large",
    rarity: "UR",
  },
  "460mm三連装砲T0": {
    text: "460mm三連装砲T0",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "equips/large/34200.png",
    type: "large",
    rarity: "UR",
  },
  試作型457mm連装砲MKAT0: {
    text: "試作型457mm連装砲MKAT0",
    bg: "ui/bg5.png",
    fr: "ui/frame_5.png",
    icon: "equips/large/14500.png",
    type: "large",
    rarity: "UR",
  },
  試製410mm三連装砲T0: {
    text: "試製410mm三連装砲T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/34180.png",
    type: "large",
    rarity: "SSR",
  },
  "410mm連装砲(三式弾)T0": {
    text: "410mm連装砲(三式弾)T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/34100.png",
    type: "large",
    rarity: "SSR",
  },
  "406mm三連装砲B-37 MK-1T3": {
    text: "406mm三連装砲B-37 MK-1T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/85300.png",
    type: "large",
    rarity: "SSR",
  },
  試作型406mm三連装砲MkDT0: {
    text: "試作型406mm三連装砲MkDT0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/14360.png",
    type: "large",
    rarity: "SSR",
  },
  試作型三連装406mm主砲Model1940T0: {
    text: "試作型三連装406mm主砲Model1940T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/55900.png",
    type: "large",
    rarity: "SSR",
  },
  "試作型406mm/50三連装砲T0": {
    text: "試作型406mm/50三連装砲T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/51000.png",
    type: "large",
    rarity: "SSR",
  },
  試作型406mm三連装砲Mk6改T0: {
    text: "試作型406mm三連装砲Mk6改T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/14540.png",
    type: "large",
    rarity: "SSR",
  },
  "406mm三連装砲T3": {
    text: "406mm三連装砲T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/24200.png",
    type: "large",
    rarity: "SSR",
  },
  試作型406mmSKC連装砲T0: {
    text: "試作型406mmSKC連装砲T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/44200.png",
    type: "large",
    rarity: "SSR",
  },
  試作型406mm連装砲Mk4T0: {
    text: "試作型406mm連装砲Mk4T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/14520.png",
    type: "large",
    rarity: "SSR",
  },
  "381mm三連装砲Model1934T3": {
    text: "381mm三連装砲Model1934T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/55000.png",
    type: "large",
    rarity: "SSR",
  },
  試製381mm三連装砲T0: {
    text: "試製381mm三連装砲T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/24160.png",
    type: "large",
    rarity: "SSR",
  },
  "381mm連装砲改T0": {
    text: "381mm連装砲改T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/24300.png",
    type: "large",
    rarity: "SSR",
  },
  "380mm四連装砲Mle1935T3": {
    text: "380mm四連装砲Mle1935T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/50400.png",
    type: "large",
    rarity: "SSR",
  },
  試作型380mm三連装砲Mle1935T0: {
    text: "試作型380mm三連装砲Mle1935T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/50480.png",
    type: "large",
    rarity: "SSR",
  },
  試作型380mmSKC三連装砲T0: {
    text: "試作型380mmSKC三連装砲T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/44500.png",
    type: "large",
    rarity: "SSR",
  },
  "380mmSKC連装砲T3": {
    text: "380mmSKC連装砲T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/44100.png",
    type: "large",
    rarity: "SSR",
  },
  "356mm四連装砲T3": {
    text: "356mm四連装砲T3",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/24000.png",
    type: "large",
    rarity: "SSR",
  },
  試作型305mmSKC39三連装砲T0: {
    text: "試作型305mmSKC39三連装砲T0",
    bg: "ui/bg4.png",
    fr: "ui/frame_4.png",
    icon: "equips/large/44300.png",
    type: "large",
    rarity: "SSR",
  },
};
